In [ ]:
# Pandas is great for tabular data (rows and columns)
# Cleaning, changing, organizing, filtering, and preparing data so that it can be analyzed or used in machine learning.
# series: one-dimensional labeled array capable of holding any data type
# in series, each element has an index, which is a label that identifies the element. The index can be a string, integer, or any other data type.
# the differnce between numpy array and pandas series is that numpy array is a homogeneous data structure, which means that all the elements in the array must be of the same data type. On the other hand, pandas series is a heterogeneous data structure, which means that it can hold elements of different data types.
import pandas as pd
# data=[1,2,3,4,5]
# series=pd.Series(data)
# series
# series using dictionary
data={'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
series=pd.Series(data)
series
# printing the series with index and the data with one column

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
# Dataframe is a two-dimensional labeled data structure with columns of potentially different types. It is similar to a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.
# creating a dataframe using a dictionary
data={'Name':['John', 'Alice', 'Bob', 'Eve'], 'Age':[25, 30, 35, 40], 'City':['New York', 'Los Angeles', 'Chicago', 'Houston']}
df=pd.DataFrame(data)
df

    Name  Age         City
0   John   25     New York
1  Alice   30  Los Angeles
2    Bob   35      Chicago
3    Eve   40      Houston

In [15]:
df.loc[0]
df.head(1)
df.columns
df['Name']

0     John
1    Alice
2      Bob
3      Eve
Name: Name, dtype: str

In [16]:
df

    Name  Age         City
0   John   25     New York
1  Alice   30  Los Angeles
2    Bob   35      Chicago
3    Eve   40      Houston

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Sai", "Ravi", "Priya"],
    "Marks": [90, 80, 95]
}, index=["A", "B", "C"])
# Accessing a row using the index label
df.loc['A']
df
# accessing a row using the integer index
df.iloc[0]

Name     Sai
Marks     90
Name: A, dtype: object

In [31]:
df

    Name  Marks
A    Sai     90
B   Ravi     80
C  Priya     95

In [35]:
df.at['A', 'Marks']  # Accessing a specific value using the index label and column name
df.iat[2,1]  # Accessing a specific value using the integer index

np.int64(95)

In [36]:
df

    Name  Marks
A    Sai     90
B   Ravi     80
C  Priya     95

In [37]:
df['Subject']=['Maths', 'Science', 'English']  # Adding a new column to the DataFrame
df

    Name  Marks  Subject
A    Sai     90    Maths
B   Ravi     80  Science
C  Priya     95  English

In [ ]:
df.drop('Subject',axis=1,inplace=True)  # Dropping a column from the DataFrame permenently
# axis 1 means it is column and axis 0 means it is row. inplace=True means it will be dropped permenently from the dataframe.
df

    Name  Marks
A    Sai     90
B   Ravi     80
C  Priya     95

In [43]:
summary=df.describe()  # Displaying a summary of the DataFrame, including the number of non-null values, data types, and memory usage.
summary

           Marks
count   3.000000
mean   88.333333
std     7.637626
min    80.000000
25%    85.000000
50%    90.000000
75%    92.500000
max    95.000000

In [3]:
import pandas as pd
df=pd.read_csv('employees_practice.csv')
df

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceScore
0,101,Sai,AI,24.0,65000.0,2,Hyderabad,8
1,102,Ravi,Data Science,26.0,75000.0,3,Bangalore,9
2,103,Priya,AI,25.0,70000.0,2,Chennai,8
3,104,Anjali,HR,30.0,50000.0,5,Hyderabad,7
4,105,Karthik,AI,NaN,80000.0,4,Pune,9
5,106,Meena,Finance,28.0,55000.0,3,Chennai,6
6,107,Arjun,Data Science,24.0,72000.0,2,Bangalore,8
7,108,Sneha,HR,29.0,NaN,4,Mumbai,7
8,109,Vikram,Finance,31.0,60000.0,6,Hyderabad,8
9,110,Rohan,AI,27.0,85000.0,5,Bangalore,10
10,111,Sai,AI,24.0,65000.0,2,Hyderabad,8
11,112,Nisha,Data Science,26.0,73000.0,3,NaN,9

In [57]:
# Handling missing values in a DataFrame is an important step in data preprocessing. Pandas provides several methods to handle missing values, such as dropping rows or columns with missing values, filling missing values with a specific value or using interpolation, and more. Here are some common methods to handle missing values in a DataFrame:
df.isnull()
df.notnull().sum()  # counting the number of non-null values in each column
df.isnull().sum()  # counting the number of null values in each column
df.fillna(0)  # filling the missing values with 0
df['salary_missna']=df['Salary'].fillna(df['Salary'].mean())
df  # filling the missing values in the 'salary' column with the mean of the 'Salary' column

,EmployeeID,Name,Department,Age,Salary,Experience,City,PerformanceScore,salary_missna
0,101,Sai,AI,24.0,65000.0,2,Hyderabad,8,65000.000000
1,102,Ravi,Data Science,26.0,75000.0,3,Bangalore,9,75000.000000
2,103,Priya,AI,25.0,70000.0,2,Chennai,8,70000.000000
3,104,Anjali,HR,30.0,50000.0,5,Hyderabad,7,50000.000000
4,105,Karthik,AI,NaN,80000.0,4,Pune,9,80000.000000
5,106,Meena,Finance,28.0,55000.0,3,Chennai,6,55000.000000
6,107,Arjun,Data Science,24.0,72000.0,2,Bangalore,8,72000.000000
7,108,Sneha,HR,29.0,NaN,4,Mumbai,7,68181.818182
8,109,Vikram,Finance,31.0,60000.0,6,Hyderabad,8,60000.000000
9,110,Rohan,AI,27.0,85000.0,5,Bangalore,10,85000.000000
10,111,Sai,AI,24.0,65000.0,2,Hyderabad,8,65000.000000
11,112,Nisha,Data Science,26.0,73000.0,3,NaN,9,73000.000000

In [58]:
df.dtypes

EmployeeID            int64
Name                    str
Department              str
Age                 float64
Salary              float64
Experience            int64
City                    str
PerformanceScore      int64
salary_missna       float64
dtype: object

In [4]:
df.rename(columns={'Name': 'Employee_Name'},inplace=True)  # Renaming columns in the DataFrame
df

,EmployeeID,Employee_Name,Department,Age,Salary,Experience,City,PerformanceScore
0,101,Sai,AI,24.0,65000.0,2,Hyderabad,8
1,102,Ravi,Data Science,26.0,75000.0,3,Bangalore,9
2,103,Priya,AI,25.0,70000.0,2,Chennai,8
3,104,Anjali,HR,30.0,50000.0,5,Hyderabad,7
4,105,Karthik,AI,NaN,80000.0,4,Pune,9
5,106,Meena,Finance,28.0,55000.0,3,Chennai,6
6,107,Arjun,Data Science,24.0,72000.0,2,Bangalore,8
7,108,Sneha,HR,29.0,NaN,4,Mumbai,7
8,109,Vikram,Finance,31.0,60000.0,6,Hyderabad,8
9,110,Rohan,AI,27.0,85000.0,5,Bangalore,10
10,111,Sai,AI,24.0,65000.0,2,Hyderabad,8
11,112,Nisha,Data Science,26.0,73000.0,3,NaN,9

In [5]:
df['New Value']=df['Salary'].apply(lambda x: x*2)  # Applying a function to a column in the DataFrame

In [6]:
df

,EmployeeID,Employee_Name,Department,Age,Salary,Experience,City,PerformanceScore,New Value
0,101,Sai,AI,24.0,65000.0,2,Hyderabad,8,130000.0
1,102,Ravi,Data Science,26.0,75000.0,3,Bangalore,9,150000.0
2,103,Priya,AI,25.0,70000.0,2,Chennai,8,140000.0
3,104,Anjali,HR,30.0,50000.0,5,Hyderabad,7,100000.0
4,105,Karthik,AI,NaN,80000.0,4,Pune,9,160000.0
5,106,Meena,Finance,28.0,55000.0,3,Chennai,6,110000.0
6,107,Arjun,Data Science,24.0,72000.0,2,Bangalore,8,144000.0
7,108,Sneha,HR,29.0,NaN,4,Mumbai,7,NaN
8,109,Vikram,Finance,31.0,60000.0,6,Hyderabad,8,120000.0
9,110,Rohan,AI,27.0,85000.0,5,Bangalore,10,170000.0
10,111,Sai,AI,24.0,65000.0,2,Hyderabad,8,130000.0
11,112,Nisha,Data Science,26.0,73000.0,3,NaN,9,146000.0

In [8]:
# Data aggregation is the process of combining multiple data points into a single summary value. In pandas, aggregation can be performed using various methods such as sum(), mean(), median(), min(), max(), count(), etc. Aggregation can be applied to a single column or multiple columns of a DataFrame. Here are some examples of aggregation in pandas:
# Data grouping is the process of grouping data based on one or more columns and applying an aggregation function to each group. In pandas, grouping can be performed using the groupby() method. Here are some examples of grouping in pandas:
# grouped_sum=df.groupby(['Department','City'])['Salary'].sum()  # Grouping the data by 'Department' and 'City' columns and calculating the sum of 'Salary' for each group
# grouped_sum
aggregate_funtion=df.groupby(['City'])['Salary'].agg(['sum','mean','count'])
aggregate_funtion  # Grouping the data by 'City' column and calculating the sum, mean, and count of 'Salary' for each group

                sum          mean  count
City
Bangalore  232000.0  77333.333333      3
Chennai    125000.0  62500.000000      2
Hyderabad  240000.0  60000.000000      4
Mumbai          0.0           NaN      0
Pune        80000.0  80000.000000      1

In [16]:
# Merging and joining data in pandas is the process of combining two or more DataFrames based on a common column or index. Pandas provides several methods for merging and joining data, such as merge(), join(), concat(), etc. Here are some examples of merging and joining data in pandas:
df1=pd.DataFrame({'key':['A','B','C','D'],'value':[1,2,3,4]})
df2=pd.DataFrame({'key':['B','D','E','F'],'value':[5,6,7,8]})
# merged_df=pd.merge(df1,df2,on='key',how='inner')  #
# merged_df=pd.merge(df1,df2,on="key",how="outer")
# merged_df=pd.merge(df1,df2,on="key",how="left") 
merged_df=pd.merge(df1,df2,on="key",how="right") 
# merged_df  # Merging the two DataFrames on the 'key' column using a left join
merged_df  # Merging the two DataFrames on the 'key' column using an inner join  # Merging the two DataFrames on the 'key' column using an inner join

  key  value_x  value_y
0   B      2.0        5
1   D      4.0        6
2   E      NaN        7
3   F      NaN        8

In [24]:
# Reading data from various data sources is an important step in data analysis. Pandas provides several methods to read data from different sources, such as CSV files, Excel files, SQL databases, and more. Here are some examples of reading data from various data sources in pandas:
# df=pd.read_csv('employees_practice.csv')  # Reading data from a CSV file
# give me the commands for different data sources like excel, sql, json, html, parquet, feather, hdf5, msgpack, clipboard, stata, sas, pickle, gbq, orc, and google sheets.
# for html pd.read_html('url')  # Reading data from an HTML file
# for excel pd.read_excel('file.xlsx')  # Reading data from an Excel file
# for json pd.read_json('file.json')  # Reading data from a JSON file
# we can use match as well while reading data from various data sources. For example, we can use the match parameter in the read_csv() method to specify a regular expression pattern to match the file name. This can be useful when we have multiple files with similar names and we want to read only the files that match a specific pattern. Here is an example:
# url = "https://en.wikipedia.org/wiki/Artificial_general_intelligence"
# df_url=pd.read_html(url,match='History',header=0)[0]  # Reading data from an HTML file and matching the table with the header 'History'

In [18]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.3-cp314-cp314-win_amd64.whl.metadata (3.4 kB)
Downloading lxml-6.1.3-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.1 MB 6.4 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.1 MB 18.8 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 8.8 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.3

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip